version: "3.7"
services:
 app:
   build:
     dockerfile: Dockerfile
   image: mydockerapp
   ports:
     - "80:8000"
   container_name: mydockerapp
   working_dir: /var/www/
   volumes:
     - ./:/var/www
